### ISSUE TITLE
Interested contributors

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/IBM#2]
Comment taken from here - https://github.com/testthedocs/vale-styles/issues/7#issuecomment-597503801

There are a group of people interested in contributing to this style:

@themr0c, @rkratky, @MichalMaler, @boczkowska, @robin-owen @gaurav-nelson and myself. Not sure if it's easier for you to add us as contributors or just accept PRs?

**Comment by jdkato** [comment]
I'll add everyone as a contributor so that every change doesn't have to go through me first.
